# ACCESS-NRI Intake catalog for loading model output

This tutorial demonstrates how to use the ACCESS-NRI Intake catalog to load model or other output.

⚠️ **Membership to project `xp65` is required to access the ACCESS-NRI Intake catalog** ⚠️

This is a concise version of the longer [ACCESS-NRI Intake catalog documentation](https://access-nri-intake-catalog.readthedocs.io/) and related [COSIMA training workshop](https://github.com/ACCESS-Hive/cosima-training-workshop-2023/blob/main/Intake.ipynb). Users are encouraged to refer to these for more detail and demonstrations.

Requirements: The `conda/analysis3` module from `/g/data/xp65/public/modules`.
___
### There is also an interactive, web based view into the intake catalog, which will let you click through the catalog and generate the code for you.

https://access-nri.github.io/interactive-data-catalogue/
__For beginners, or troubleshooting, or just finding a dataset you aren't familiar with, this is a great place to start!__ It will:
- Show you all the catalog entries, their metadata, and the experiments they encode
- Generate quickstart code you can copy and paste into an ARE session in order to load data
- Allow you to share searches via URLs
- Disambiguate between dataset dictionaries and a single dataset (more on that later!) for you.

__The Interactive Data Catalogue was built as a tool to address, avoid, or make trivial many of the common difficulties and questions that this notebook tries to train people in using.__

# Start a dask Client

This is not specific to using the ACCESS-NRI Intake catalog, but it's useful!

In [2]:
from dask.distributed import Client

client = Client(threads_per_worker=1)
client

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.10/lib/python3.12/site-packages/distributed/node.py:188: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 46351 instead
  warnings.warn(

# Opening and searching the catalog

To use the ACCESS-NRI Intake catalog, we need to import `intake`

In [3]:
import intake

We can open the catalog as follows

In [4]:
catalog = intake.cat.access_nri

The returned object `catalog` is an instance of the ACCESS-NRI Intake catalog that we can use to find and load data.

Printing the `catalog` object will return a dataframe of experiments that you can browse:

In [5]:
catalog

You can also search based on the columns in this dataframe to find experiments that are relevant to you. For example, you might be interested in all ACCESS-OM2 experiments that have the variable `"surface_salt"` at daily frequency. There are 6 such experiments currently available through the catalog:

In [6]:
catalog.search(model="ACCESS-OM2", variable="surface_salt", frequency="1day")

/jobfs/182289729.gadi-pbs/ipykernel_1105349/1633839607.py:1: UserWarning: Value aliasing: model='ACCESS-OM2' → model=['ACCESS-OM2','ACCESS-OM2']
  catalog.search(model="ACCESS-OM2", variable="surface_salt", frequency="1day")

# Opening data

There are [multiple ways](https://access-nri-intake-catalog.readthedocs.io/en/latest/usage/quickstart.html#loading-intake-sources) to open data from the experiments in `catalog`. Here we'll demonstrate how to do this when you know the name of the experiment you are interested in, since this typical for COSIMA users.

For example, we can open monthly data for the `surface_salt` variable in the `01deg_jra55v13_ryf9091` experiment as follows:

In [7]:
experiment = "01deg_jra55v13_ryf9091"
variable = "surface_salt"

In [8]:
data_ic = catalog[experiment].search(
    variable=variable, 
    frequency="1mon"
).to_dask()

In [9]:
data_ic["surface_salt"]

<xarray.DataArray 'surface_salt' (time: 3360, yt_ocean: 2700, xt_ocean: 3600)> Size: 131GB
dask.array<concatenate, shape=(3360, 2700, 3600), dtype=float32, chunksize=(3, 2025, 2700), chunktype=numpy.ndarray>
Coordinates:
  * time      (time) object 27kB 1900-01-16 12:00:00 ... 2179-12-16 12:00:00
  * yt_ocean  (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.89 89.94 89.98
  * xt_ocean  (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.75 79.85 79.95
Attributes:
    long_name:      Practical Salinity
    units:          psu
    valid_range:    [-10. 100.]
    cell_methods:   time: mean
    time_avg_info:  average_T1,average_T2,average_DT
    standard_name:  sea_surface_salinity

# Some important facts

There are a few important facts in the ACCESS-NRI Intake catalog that users should be aware of.

## 1. The catalog returns `Datasets` (not `Dataarray`s)

This is because with the catalog you can load multiple variables into a single dataset with a single call (when these variables are in the same file). For example,

In [10]:
data_ic_multivar = catalog[experiment].unwrap().search(
    variable=["surface_salt", "surface_temp"], 
    frequency="1mon"
).to_dask()

In [11]:
data_ic_multivar

<xarray.Dataset> Size: 261GB
Dimensions:       (time: 3360, yt_ocean: 2700, xt_ocean: 3600)
Coordinates:
  * time          (time) object 27kB 1900-01-16 12:00:00 ... 2179-12-16 12:00:00
  * yt_ocean      (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.94 89.98
  * xt_ocean      (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.85 79.95
Data variables:
    surface_temp  (time, yt_ocean, xt_ocean) float32 131GB dask.array<chunksize=(3, 2025, 2700), meta=np.ndarray>
    surface_salt  (time, yt_ocean, xt_ocean) float32 131GB dask.array<chunksize=(3, 2025, 2700), meta=np.ndarray>
Attributes:
    filename:                         ocean_month.nc
    title:                            ACCESS-OM2-01
    grid_type:                        mosaic
    grid_tile:                        1
    intake_esm_vars:                  ['surface_temp', 'surface_salt']
    intake_esm_attrs:filename:        ocean_month.nc
    intake_esm_attrs:file_id:         ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:...
    intake_esm_attrs:frequency:       1mon
    intake_esm_attrs:realm:           ocean
    intake_esm_attrs:temporal_label:  mean
    intake_esm_attrs:_data_format_:   netcdf
    intake_esm_dataset_key:           ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:...

## 2. The catalog knows which files make up distinct datasets

The catalog knows which files make up distinct datasets and provides methods to open multiple datasets from a single query. We can run the equivalent to the cell above using the catalog, using `to_dataset_dict()` rather than `to_dask()`. Doing so returns a dictionary containing Datasets of the variable at all the available frequencies (daily and monthly in this case).

In [12]:
data_ic_multifreq = catalog[experiment].search(variable=variable).to_dataset_dict()

--> The keys in the returned dictionary of datasets are constructed as follows:
	'file_id.temporal_label'

In [13]:
data_ic_multifreq

{'ocean.1day.nv:2.xt_ocean:3600.xu_ocean:3600.yt_ocean:2700.yu_ocean:2700.mean': <xarray.Dataset> Size: 610GB
 Dimensions:       (time: 15695, yt_ocean: 2700, xt_ocean: 3600)
 Coordinates:
   * time          (time) object 126kB 2137-01-01 12:00:00 ... 2179-12-31 12:0...
   * yt_ocean      (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.94 89.98
   * xt_ocean      (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.85 79.95
 Data variables:
     surface_salt  (time, yt_ocean, xt_ocean) float32 610GB dask.array<chunksize=(3, 2025, 2700), meta=np.ndarray>
 Attributes:
     filename:                         ocean_daily.nc
     title:                            ACCESS-OM2-01
     grid_type:                        mosaic
     grid_tile:                        1
     intake_esm_vars:                  ['surface_salt']
     intake_esm_attrs:filename:        ocean_daily.nc
     intake_esm_attrs:file_id:         ocean.1day.nv:2.xt_ocean:3600.xu_ocean:...
     intake_esm_attrs:frequency:       1day
     intake_esm_attrs:realm:           ocean
     intake_esm_attrs:temporal_label:  mean
     intake_esm_attrs:_data_format_:   netcdf
     intake_esm_dataset_key:           ocean.1day.nv:2.xt_ocean:3600.xu_ocean:...,
 'ocean.1day.nv:2.xt_ocean:3600.yt_ocean:2700.mean': <xarray.Dataset> Size: 3TB
 Dimensions:       (time: 65885, yt_ocean: 2700, xt_ocean: 3600)
 Coordinates:
   * time          (time) object 527kB 1956-04-01 12:00:00 ... 2136-12-31 12:0...
   * yt_ocean      (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.94 89.98
   * xt_ocean      (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.85 79.95
 Data variables:
     surface_salt  (time, yt_ocean, xt_ocean) float32 3TB dask.array<chunksize=(3, 2025, 2700), meta=np.ndarray>
 Attributes: (12/15)
     filename:                                ocean_daily.nc
     title:                                   ACCESS-OM2-01
     grid_type:                               mosaic
     grid_tile:                               1
     intake_esm_vars:                         ['surface_salt']
     intake_esm_attrs:filename:               ocean_daily.nc
     ...                                      ...
     intake_esm_attrs:variable_long_name:     Length of average period,Start t...
     intake_esm_attrs:variable_cell_methods:  ,,,time: mean,time: mean,time: m...
     intake_esm_attrs:realm:                  ocean
     intake_esm_attrs:temporal_label:         mean
     intake_esm_attrs:_data_format_:          netcdf
     intake_esm_dataset_key:                  ocean.1day.nv:2.xt_ocean:3600.yt...,
 'ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:3600.yt_ocean:2700.yu_ocean:2700.mean': <xarray.Dataset> Size: 131GB
 Dimensions:       (time: 3360, yt_ocean: 2700, xt_ocean: 3600)
 Coordinates:
   * time          (time) object 27kB 1900-01-16 12:00:00 ... 2179-12-16 12:00:00
   * yt_ocean      (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.94 89.98
   * xt_ocean      (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.85 79.95
 Data variables:
     surface_salt  (time, yt_ocean, xt_ocean) float32 131GB dask.array<chunksize=(3, 2025, 2700), meta=np.ndarray>
 Attributes:
     filename:                         ocean_month.nc
     title:                            ACCESS-OM2-01
     grid_type:                        mosaic
     grid_tile:                        1
     intake_esm_vars:                  ['surface_salt']
     intake_esm_attrs:filename:        ocean_month.nc
     intake_esm_attrs:file_id:         ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:...
     intake_esm_attrs:frequency:       1mon
     intake_esm_attrs:realm:           ocean
     intake_esm_attrs:temporal_label:  mean
     intake_esm_attrs:_data_format_:   netcdf
     intake_esm_dataset_key:           ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:...}

Alternatively, multiple datasets can be opened directly into an [xarray datatree](https://docs.xarray.dev/en/stable/generated/xarray.DataTree.html) by calling `to_datatree` rather than `to_dataset_dict`. For example:

In [14]:
data_ic_datatree = catalog[experiment].search(variable=variable).to_datatree()

--> The keys in the returned dictionary of datasets are constructed as follows:
	'file_id/temporal_label'

In [15]:
data_ic_datatree

<xarray.DataTree>
Group: /
├── Group: /ocean.1day.nv:2.xt_ocean:3600.xu_ocean:3600.yt_ocean:2700.yu_ocean:2700
│   └── Group: /ocean.1day.nv:2.xt_ocean:3600.xu_ocean:3600.yt_ocean:2700.yu_ocean:2700/mean
│           Dimensions:       (time: 15695, yt_ocean: 2700, xt_ocean: 3600)
│           Coordinates:
│             * time          (time) object 126kB 2137-01-01 12:00:00 ... 2179-12-31 12:0...
│             * yt_ocean      (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.94 89.98
│             * xt_ocean      (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.85 79.95
│           Data variables:
│               surface_salt  (time, yt_ocean, xt_ocean) float32 610GB dask.array<chunksize=(3, 2025, 2700), meta=np.ndarray>
│           Attributes:
│               filename:                         ocean_daily.nc
│               title:                            ACCESS-OM2-01
│               grid_type:                        mosaic
│               grid_tile:                        1
│               intake_esm_vars:                  ['surface_salt']
│               intake_esm_attrs:filename:        ocean_daily.nc
│               intake_esm_attrs:file_id:         ocean.1day.nv:2.xt_ocean:3600.xu_ocean:...
│               intake_esm_attrs:frequency:       1day
│               intake_esm_attrs:realm:           ocean
│               intake_esm_attrs:temporal_label:  mean
│               intake_esm_attrs:_data_format_:   netcdf
│               intake_esm_dataset_key:           ocean.1day.nv:2.xt_ocean:3600.xu_ocean:...
├── Group: /ocean.1day.nv:2.xt_ocean:3600.yt_ocean:2700
│   └── Group: /ocean.1day.nv:2.xt_ocean:3600.yt_ocean:2700/mean
│           Dimensions:       (time: 65885, yt_ocean: 2700, xt_ocean: 3600)
│           Coordinates:
│             * time          (time) object 527kB 1956-04-01 12:00:00 ... 2136-12-31 12:0...
│             * yt_ocean      (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.94 89.98
│             * xt_ocean      (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.85 79.95
│           Data variables:
│               surface_salt  (time, yt_ocean, xt_ocean) float32 3TB dask.array<chunksize=(3, 2025, 2700), meta=np.ndarray>
│           Attributes: (12/15)
│               filename:                                ocean_daily.nc
│               title:                                   ACCESS-OM2-01
│               grid_type:                               mosaic
│               grid_tile:                               1
│               intake_esm_vars:                         ['surface_salt']
│               intake_esm_attrs:filename:               ocean_daily.nc
│               ...                                      ...
│               intake_esm_attrs:variable_long_name:     Length of average period,Start t...
│               intake_esm_attrs:variable_cell_methods:  ,,,time: mean,time: mean,time: m...
│               intake_esm_attrs:realm:                  ocean
│               intake_esm_attrs:temporal_label:         mean
│               intake_esm_attrs:_data_format_:          netcdf
│               intake_esm_dataset_key:                  ocean.1day.nv:2.xt_ocean:3600.yt...
└── Group: /ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:3600.yt_ocean:2700.yu_ocean:2700
    └── Group: /ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:3600.yt_ocean:2700.yu_ocean:2700/mean
            Dimensions:       (time: 3360, yt_ocean: 2700, xt_ocean: 3600)
            Coordinates:
              * time          (time) object 27kB 1900-01-16 12:00:00 ... 2179-12-16 12:00:00
              * yt_ocean      (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.94 89.98
              * xt_ocean      (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.85 79.95
            Data variables:
                surface_salt  (time, yt_ocean, xt_ocean) float32 131GB dask.array<chunksize=(3, 2025, 2700), meta=np.ndarray>
            Attributes:
                filename:                         ocean_month.nc
                title:                            ACCESS-OM2-01
                grid_type:                        mosaic
                grid_tile:                        1
                intake_esm_vars:                  ['surface_salt']
                intake_esm_attrs:filename:        ocean_month.nc
                intake_esm_attrs:file_id:         ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:...
                intake_esm_attrs:frequency:       1mon
                intake_esm_attrs:realm:           ocean
                intake_esm_attrs:temporal_label:  mean
                intake_esm_attrs:_data_format_:   netcdf
                intake_esm_dataset_key:           ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:...

## If you have multiple datasets, you can use the interactive catalog to guide you down to a single dataset:
https://access-nri.github.io/interactive-data-catalogue/#/datastore/01deg_jra55v13_ryf9091?variable_filter=surface_salt

- The link above takes us to the same search in the interactive catalog, which tells us our search contains 3 datasets.
- We can see if we open the frequency selector on this page that __both monthly and daily data are available__.
- Selecting daily data gives us two datasets, and the quickstart code still tells us to load a dataset dict.
- Selecting monthly data gives us a single dataset, and the quickstart code changes to load a dataset!
    - So if we want a single dataset, we can either filter for monthly data too (https://access-nri.github.io/interactive-data-catalogue/#/datastore/01deg_jra55v13_ryf9091?variable_filter=surface_salt&frequency_filter=1mon), or
    -  Daily and do some further filtering, eg. (https://access-nri.github.io/interactive-data-catalogue/#/datastore/01deg_jra55v13_ryf9091?variable_filter=surface_salt&frequency_filter=1day&file_id_filter=ocean.1day.nv:2.xt_ocean:3600.yt_ocean:2700)
    - The further filtering reveals we have both 2D (ocean surface) and 3D (full depth) fields for daily data.

__In general, you will find it quicker to use the interactive catalog to search for what you need - you won't need to learn intake syntax to get what you're after, just click through by hand. Once you've got what you need, you can copy the code and open an ARE session.__

## 3. The frequency vocabulary:

In the catalog, frequency follows a standard vocabulary that is very similar to CMIP6:

```python
"fx" # fixed
"subhr" # subhourly
"<int>hr" # hourly
"<int>day" # daily
"<int>mon" # monthly
"<int>yr" # yearly
"<int>dec" # decadal
```

## 4. Method for passing keyword arguments

With the catalog, keyword argments for xarray's `open_dataset` and `combine_by_coords` functions are passed separately to `to_dask` (or `to_dataset_dict`). For example:

In [16]:
xarray_open_kwargs=dict(
    chunks={"xt_ocean": -1, "yt_ocean": -1}
)
xarray_combine_by_coords_kwargs=dict(
    compat="override",
    data_vars="minimal",
    coords="minimal"
)

data_ic_kw = catalog[experiment].search(
    variable=variable, 
    frequency="1mon"
).to_dask(
    xarray_open_kwargs=xarray_open_kwargs,
    xarray_combine_by_coords_kwargs=xarray_combine_by_coords_kwargs,
)

## 5. Catalog does not allow search by start and end date (straightforwardly)

It's not straightforwardly possible to query on a time range with the Intake catalog.

We can always slice the time axis afterwards though. That is, with the catalog you'd just do:

In [17]:
data_ic = catalog[experiment].search(
    variable=variable, 
    frequency="1mon"
).to_dask()

start_time = "2000-01-01"
end_time = "2180-01-01"

data_ic_times = data_ic.sel(time=slice(start_time, end_time))

which takes a few seconds longer than filtering before opening via regex (see below).

This difference is acceptable because the opening of datasets is a parallelized task that is done [lazily](https://docs.xarray.dev/en/stable/user-guide/dask.html#parallel-computing-with-dask),  so opening all files and reducing the times using xarray's `sel` methods doesn't add too much overhead. In most cases where the overhead of opening the files seems large, this can be reduced through sensible choices of keyword arguments provided to `open_dataset` and `combine_by_coords` - see the xarray documentation on [Reading multi-file datasets](https://docs.xarray.dev/en/stable/user-guide/io.html#reading-multi-file-datasets) for details.

If you are brave, you can do the same thing via regular expressions (regex). This is a way of telling the computer to match a variety of text outputs, depending on their content and stucture.

See [the Python regex documentation for more info](https://docs.python.org/3/library/re.html) - or ask an LLM, they're very good at regex.

For the example above, we could match all start times up to 2180-01-01 and then end times up to that using:

In [18]:
data_ic_regex_filtered = catalog[experiment].search(
    variable=variable, 
    frequency="1mon",
    start_date="2[0-1][0-9][0-9].*", # Match anything from 2000-... to 2199-...
    end_date="2...-..-.*",
).to_dask()
data_ic_regex_filtered

<xarray.Dataset> Size: 84GB
Dimensions:       (time: 2160, yt_ocean: 2700, xt_ocean: 3600)
Coordinates:
  * time          (time) object 17kB 2000-01-16 12:00:00 ... 2179-12-16 12:00:00
  * yt_ocean      (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.94 89.98
  * xt_ocean      (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.85 79.95
Data variables:
    surface_salt  (time, yt_ocean, xt_ocean) float32 84GB dask.array<chunksize=(3, 2700, 3600), meta=np.ndarray>
Attributes: (12/17)
    filename:                                 ocean_month.nc
    title:                                    ACCESS-OM2-01
    grid_type:                                mosaic
    grid_tile:                                1
    intake_esm_vars:                          ['surface_salt']
    intake_esm_attrs:filename:                ocean_month.nc
    ...                                       ...
    intake_esm_attrs:variable_cell_methods:   ,,,time: mean,time: mean,time: ...
    intake_esm_attrs:variable_units:          days,days since 1900-01-01 00:0...
    intake_esm_attrs:realm:                   ocean
    intake_esm_attrs:temporal_label:          mean
    intake_esm_attrs:_data_format_:           netcdf
    intake_esm_dataset_key:                   ocean.1mon.nv:2.xt_ocean:3600.x...

You might notice that this regex expression is very difficult to understand. For all but the simplest (things like `rm ./*` in your terminal to clear out a directory is a simple regex), they can be extremely difficult to read. Unless filtering on dates once you've already opened the dataset is taking an extremely long time, stick with that approach!

## 6. Applying a preprocessing function

You can use `xarray`'s preprocess function to apply a function to each dataset prior to `intake`'s concatenation. In some cases, this can make the loading into memory fast. 

For example:

In [19]:
def select_region(ds):
    ds = ds.sel(xt_ocean=slice(-230, -180), yt_ocean=slice(-50, -20))
    return ds

data_ic = catalog['01deg_jra55v13_ryf9091'].search(
    variable='surface_temp', 
    frequency="1mon"
).to_dask(preprocess=select_region)
data_ic

<xarray.Dataset> Size: 3GB
Dimensions:       (time: 3360, yt_ocean: 375, xt_ocean: 500)
Coordinates:
  * time          (time) object 27kB 1900-01-16 12:00:00 ... 2179-12-16 12:00:00
  * yt_ocean      (yt_ocean) float64 3kB -49.96 -49.9 -49.83 ... -20.12 -20.03
  * xt_ocean      (xt_ocean) float64 4kB -229.9 -229.8 -229.7 ... -180.1 -180.0
Data variables:
    surface_temp  (time, yt_ocean, xt_ocean) float32 3GB dask.array<chunksize=(3, 375, 500), meta=np.ndarray>
Attributes:
    filename:                         ocean_month.nc
    title:                            ACCESS-OM2-01
    grid_type:                        mosaic
    grid_tile:                        1
    intake_esm_vars:                  ['surface_temp']
    intake_esm_attrs:filename:        ocean_month.nc
    intake_esm_attrs:file_id:         ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:...
    intake_esm_attrs:frequency:       1mon
    intake_esm_attrs:realm:           ocean
    intake_esm_attrs:temporal_label:  mean
    intake_esm_attrs:_data_format_:   netcdf
    intake_esm_dataset_key:           ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:...

# Tips, gotchas and workarounds

## 1. Speeding up opening your datasets

Try passing the following argument to your `to_dask` or `to_dataset_dict` call:

```python
xarray_combine_by_coords_kwargs=dict(
    compat="override",
    data_vars="minimal",
    coords="minimal"
)
```

See the xarray documentation on [Reading multi-file datasets](https://docs.xarray.dev/en/stable/user-guide/io.html#reading-multi-file-datasets) for more details about these arguments.

## 2. Choosing chunksizes

Correctly choosing chunk sizes when you open datasets will greatly improve the speed of your analysis. Check out the [Chunking tutorial](https://access-nri-intake-catalog.readthedocs.io/en/latest/usage/chunking.html) in the ACCESS-NRI Intake catalog documentation.

By default, intake will use `chunks='auto'` when it opens an xarray dataset. This typically chooses a good chunking scheme for most purposes, but you may be able to improve it with some manual tuning - in the case of advanced analyses.

## 3. Loading time-invariant variables

Many COSIMA experiments include multiple repeated files containing the same fixed frequency data (e.g. grid information). You can use the option `fx` for the frequency argument, otherwise the catalog fails to concatenate these files since they don't contain a clear dimension to concatenate along.

In [20]:
data_ic_fixed = catalog[experiment].search(
    variable='area_t',
    frequency='fx'
).to_dask()
data_ic_fixed

/g/data/xp65/public/apps/med_conda/envs/analysis3-26.10/lib/python3.12/site-packages/intake_esm/source.py:316: ConcatenationWarning: Attempting to concatenate datasets without valid dimension coordinates: retaining only first dataset. Request valid dimension coordinate to silence this warning.
  warnings.warn(

<xarray.Dataset> Size: 117MB
Dimensions:   (yt_ocean: 2700, xt_ocean: 3600)
Coordinates:
  * yt_ocean  (yt_ocean) float64 22kB -81.11 -81.07 -81.02 ... 89.89 89.94 89.98
  * xt_ocean  (xt_ocean) float64 29kB -279.9 -279.8 -279.7 ... 79.75 79.85 79.95
    geolon_t  (yt_ocean, xt_ocean) float32 39MB dask.array<chunksize=(2700, 3600), meta=np.ndarray>
    geolat_t  (yt_ocean, xt_ocean) float32 39MB dask.array<chunksize=(2700, 3600), meta=np.ndarray>
Data variables:
    area_t    (yt_ocean, xt_ocean) float32 39MB dask.array<chunksize=(2700, 3600), meta=np.ndarray>
Attributes: (12/20)
    filename:                                 ocean_grid.nc
    title:                                    ACCESS-OM2-01
    grid_type:                                mosaic
    grid_tile:                                1
    intake_esm_vars:                          ['area_t']
    intake_esm_attrs:filename:                ocean_grid.nc
    ...                                       ...
    intake_esm_attrs:variable_cell_methods:   time: point,time: point,time: p...
    intake_esm_attrs:variable_units:          m^2,m^2,dimensionless,m,m,m,m,d...
    intake_esm_attrs:realm:                   ocean
    intake_esm_attrs:temporal_label:          point
    intake_esm_attrs:_data_format_:           netcdf
    intake_esm_dataset_key:                   ocean.fx.xt_ocean:3600.xu_ocean...

## 4. Determining what can be searched upon in an experiment

You can see what can be `search`ed on within an experiment with:

In [21]:
catalog[experiment].df.columns.tolist()

['filename',
 'path',
 'file_id',
 'frequency',
 'start_date',
 'end_date',
 'variable',
 'variable_long_name',
 'variable_standard_name',
 'variable_cell_methods',
 'variable_units',
 'realm',
 'temporal_label']

It can also be helpful sometimes to look at the `catalog[experiment].df` object itself, which is a dataframe of all of the files in the experiment and their metadata

In [22]:
catalog[experiment].df.head()

,filename,path,file_id,frequency,start_date,end_date,variable,variable_long_name,variable_standard_name,variable_cell_methods,variable_units,realm,temporal_label
0,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00","(ANGLE, ANGLET, HTE, HTN, NCAT, TLAT, TLON, Tsfc_m, ULAT, ULON, aice_m, aicen_m, alidf_ai_m, alidr_ai_m, alvdf_ai_m, alvdr_ai_m, blkmask, congel_m, divu_m, dxt, dxu, dyt, dyu, flatn_ai_m, fmeltt_a...","(angle grid makes with latitude line on U grid, angle grid makes with latitude line on T grid, T cell width on East side, T cell width on North side, category maximum thickness, T grid center lati...","(, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , )","(, , , , , , , time: mean, , , time: mean, time: mean, time: mean, time: mean, time: mean, time: mean, , time: mean, time: mean, , , , , time: mean, time: mean, time: mean, time: mean, time: mean,...","(radians, radians, m, m, m, degrees_north, degrees_east, C, degrees_north, degrees_east, 1, 1, %, %, %, %, , cm/day, %/day, m, m, m, m, W/m^2, W/m^2, W/m^2, cm/day, day of year, kg/m^2/s, kg/m^2/s...",seaIce,mean
1,iceh.1900-02.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-02.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-02-01, 00:00:00","1900-03-01, 00:00:00","(ANGLE, ANGLET, HTE, HTN, NCAT, TLAT, TLON, Tsfc_m, ULAT, ULON, aice_m, aicen_m, alidf_ai_m, alidr_ai_m, alvdf_ai_m, alvdr_ai_m, blkmask, congel_m, divu_m, dxt, dxu, dyt, dyu, flatn_ai_m, fmeltt_a...","(angle grid makes with latitude line on U grid, angle grid makes with latitude line on T grid, T cell width on East side, T cell width on North side, category maximum thickness, T grid center lati...","(, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , )","(, , , , , , , time: mean, , , time: mean, time: mean, time: mean, time: mean, time: mean, time: mean, , time: mean, time: mean, , , , , time: mean, time: mean, time: mean, time: mean, time: mean,...","(radians, radians, m, m, m, degrees_north, degrees_east, C, degrees_north, degrees_east, 1, 1, %, %, %, %, , cm/day, %/day, m, m, m, m, W/m^2, W/m^2, W/m^2, cm/day, day of year, kg/m^2/s, kg/m^2/s...",seaIce,mean
2,iceh.1900-03.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-03.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-03-01, 00:00:00","1900-04-01, 00:00:00","(ANGLE, ANGLET, HTE, HTN, NCAT, TLAT, TLON, Tsfc_m, ULAT, ULON, aice_m, aicen_m, alidf_ai_m, alidr_ai_m, alvdf_ai_m, alvdr_ai_m, blkmask, congel_m, divu_m, dxt, dxu, dyt, dyu, flatn_ai_m, fmeltt_a...","(angle grid makes with latitude line on U grid, angle grid makes with latitude line on T grid, T cell width on East side, T cell width on North side, category maximum thickness, T grid center lati...","(, , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , )","(, , , , , , , time: mean, , , time: mean, time: mean, time: mean, time: mean, time: mean, time: mean, , time: mean, time: mean, , , , , time: mean, time: mean, time: mean, time: mean, time: mean,...","(radians, radians, m, m, m, degrees_north, degrees_east, C, degrees_north, degrees_east, 1, 1, %, %, %, %, , cm/day, %/day, m, m, m, m, W/m^2, W/m^2, W/m^2, cm/day, day of year, kg/m^2/s, kg/m^2/s...",seaIce,mean
3,ocean.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ocean/ocean.nc,ocean.3mon.grid_xt_ocean:3600.grid_xu_ocean:3600.grid_yt_ocean:2700.grid_yu_ocean:2700.neutral:80.neutralrho_edges:81.nv:2.potrho:80.potrho_edges:81.st_edges_ocean:76.st_ocean:75.sw_edges_ocean:76...,3mon,"1900-01-01, 00:00:00","1900-04-01, 00:00:00","(age_global, average_DT, average_T1, average_T2, dzt, grid_xt_ocean, grid_xu_ocean, grid_yt_ocean, grid_yu_ocean, neutral, neutralrho_edges, nv, pot_rho_0, pot_temp, potrho, potrho_edges, rho, sal...","(Age (global), Length of average period, Start time for average period, End time for average period, t-cell thickness, tcell longitude, ucell longitude, tcell latitude, ucell latitude, neutral den...","(sea_water_age_since_surface_contact, , , , cell_thickness, , , , , , , , sea_water_potential_density, sea_water_potential_temperature, , , , sea_water_salinity, , , , , , , , , , ocean_mass_x_tra...","(time: mean, , , , time: mean, , , , , , , , time: mean, time: mean, , , time: mean, time: mean, , , , , time: mean, time: mean, time: mean, , , time: mean, time: mean, time: mean, time: mean, tim...","(yr, days, days since 1900-01-01 00:00:00, days since 1900-01-01 00:00:00, m, degrees_E, degrees_E, degrees_N, degrees_N, kg/m^3, kg/m^3, none, kg/m^3, degrees K, kg/m^3, kg/m^3, kg/m^3, psu, mete...",ocean,mean
4,ocean_grid.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ocean/ocean_grid.nc,ocean.fx.xt_ocean:3600.xu_ocean:3600.yt_ocean:2700.yu_ocean:2700,fx,"1900-04-01, 00:00:00","1900-04-01, 00:00:00","(area_t, area_u, drag_coeff, dxt, dxu, dyt, dyu, geolat_c, geolat_t, geolon_c, geolon_t, ht, hu, kmt, kmu, time, xt_ocean, xu_ocean, yt_ocean, yu_ocean)","(tracer cell area, velocity cell area, Dimensionless bottom drag coefficient, ocean dxt on t-cells, ocean dxu on u-cells, ocean dyt on t-cells, ocean dyu on u-cells, uv latitude, tracer latitude, ...","(, , , , , , , , , , , sea_floor_depth_below_geoid, , , , , , , , )","(time: point, time: point, time: point, time: point, time: point, time: point, time: point, time: point, time: point, time: point, time: point, time: point, time: point, time: point, time: point, ...","(m^2, m^2, dimensionless, m, m, m, m, degrees_N, degrees_N, degrees_E, degrees_E, m, m, dimensionless, dimensionless, days since 1900-01-01 00:00:00, degrees_E, degrees_E, degrees_N, degrees_N)",ocean,point

## 5. Finding all variables in a catalog

You can get a list of all available variable names from an experiment with:

In [23]:
variables = catalog.search(name=experiment).unique().variable
print(variables)

['flatn_ai_m', 'xu_ocean_sub02', 'ty_trans_int_z', 'xu_ocean', 'neutralrho_edges', 'temp_tendency', 'vhrho_nt', 'age_global', 'eta_t', 'uatm_m', 'sens_heat', 'time_bounds', 'NCAT', 'total_ocean_river', 'TLON', 'total_ocean_river_heat', 'hs_m', 'total_ocean_sfc_salt_flux_coupler', 'usurf', 'grid_xu_ocean', 'sea_level', 'fswup_m', 'salt_surface_ave', 'ty_trans_submeso', 'tx_trans', 'tau_y', 'neutral', 'opening_m', 'wfiform', 'temp_xflux_adv', 'wfimelt', 'uarea', 'temp_yflux_adv', 'xt_ocean', 'fsalt_ai_m', 'sfc_hflux_pme', 'melt', 'grid_xt_ocean', 'strairx_m', 'temp_vdiffuse_impl', 'geolon_t', 'total_ocean_swflx_vis', 'surface_temp', 'average_T2', 'temp_rivermix', 'average_DT', 'divu_m', 'total_ocean_fprec', 'potrho_edges', 'total_ocean_salt', 'vsurf', 'sw_edges_ocean', 'fmelttn_ai_m', 'grid_yu_ocean', 'lw_heat', 'dzt', 'geolon_c', 'mld', 'xu_ocean_sub01', 'temp_surface_ave', 'lprec', 'sss_m', 'uocn_m', 'dyt', 'fmeltt_ai_m', 'ty_trans_rho', 'tx_trans_int_z', 'swflx', 'grid_yt_ocean', 'fprec_melt_heat', 'yu_ocean_sub01', 'ULON', 'vocn_m', 'temp_vdiffuse_diff_cbt_conv', 'HTE', 'alidf_ai_m', 'yt_ocean', 'temp_global_ave', 'surface_salt', 'fprec', 'sst_m', 'ULAT', 'buoyfreq2_wt', 'tmask', 'total_ocean_lprec', 'temp', 'salt_global_ave', 'runoff', 'pot_rho_0', 'tx_trans_submeso', 'total_ocean_swflx', 'bih_fric_v', 'tx_trans_rho', 'uhrho_et', 'passive_ross', 'sfc_hflux_coupler', 'total_ocean_evap_heat', 'total_ocean_heat', 'ht', 'total_ocean_hflux_coupler', 'tau_x', 'total_ocean_calving_melt_heat', 'st_edges_ocean', 'potrho', 'rho', 'ty_trans_nrho_submeso', 'nv', 'time', 'pme_net', 'ty_trans', 'fsalt_m', 'pbot_t', 'evap_heat', 'HTN', 'pot_rho_2', 'blkmask', 'ANGLE', 'aice_m', 'passive_weddell', 'sfc_salt_flux_ice', 'ke_tot', 'total_ocean_sens_heat', 'drag_coeff', 'yt_ocean_sub01', 'rhoave', 'yu_ocean', 'area_t', 'passive_adelie', 'evap', 'xt_ocean_sub01', 'net_sfc_heating', 'sfc_hflux_from_runoff', 'frazil_3d_int_z', 'tarea', 'u', 'total_ocean_melt', 'u_dot_grad_vert_pv', 'eta_global', 'pme_river', 'total_ocean_evap', 'v', 'dxu', 'vatm_m', 'sig1_m', 'sfc_salt_flux_restore', 'sfc_salt_flux_coupler', 'bih_fric_u', 'hu', 'salt', 'river', 'total_ocean_hflux_evap', 'alvdf_ai_m', 'kmu', 'frazil_m', 'frazil_3d', 'scalar_axis', 'pe_tot', 'strength_m', 'kmt', 'temp_submeso', 'Tsfc_m', 'vert_pv', 'total_ocean_runoff_heat', 'average_T1', 'vvel_m', 'sw_ocean', 'wt', 'area_u', 'dyu', 'yt_ocean_sub02', 'pot_rho_1', 'temp_advection', 'congel_m', 'pot_temp', 'dxt', 'st_ocean', 'geolat_c', 'passive_prydz', 'mlt_onset_m', 'sig2_m', 'alidr_ai_m', 'frz_onset_m', 'total_ocean_fprec_melt_heat', 'total_ocean_calving', 'sea_levelsq', 'TLAT', 'uvel_m', 'vicen_m', 'total_ocean_runoff', 'strairy_m', 'total_ocean_hflux_prec', 'total_net_sfc_heating', 'aicen_m', 'xt_ocean_sub02', 'shear_m', 'temp_nonlocal_KPP', 'alvdr_ai_m', 'total_ocean_pme_river', 'total_ocean_calving_heat', 'yu_ocean_sub02', 'ANGLET', 'geolat_t', 'total_ocean_lw_heat', 'sw_heat', 'hi_m']

### We could similarly filter for any of the keys in our catalog - see the intake dataframe catalog below

(N.B This is the top level catalog we search here - it works exactly the same way)

In [24]:
catalog.search(name=experiment)

In [25]:
catalog.search(name=experiment, realm = 'ocean')

/jobfs/182289729.gadi-pbs/ipykernel_1105349/331518176.py:1: UserWarning: Value aliasing: realm='ocean' → realm=['ocean','ocean']
  catalog.search(name=experiment, realm = 'ocean')

In [26]:
# Lets pull out all the unique frequencies, just like we did for variable above
catalog.search(name=experiment, realm='ocean').unique().frequency

/jobfs/182289729.gadi-pbs/ipykernel_1105349/3796279993.py:2: UserWarning: Value aliasing: realm='ocean' → realm=['ocean','ocean']
  catalog.search(name=experiment, realm='ocean').unique().frequency

['3mon', '1mon', 'fx', '1day', '3hr']

We could also open the experiment (using square brackets) to search for variables, frequencies, etc. - but this opens the datastore: see how the output of the cell below is displayed differently.

If we open the datastore: 
1. It is slower - opening datastores requires extra work
2. The items we can search on might change - the datastore below contains no model field, for example.

The opened datastore can contain extra information, eg. `variable_long_name` below - so sometimes you might want to open it to search the datastore. In general, try to use `catalog.search(name='xyz',...)` before you use `catalog['xyz'].search(...)`, though.

In [27]:
catalog[experiment]

For more information about the available variables, you can use the following command function - just copy and paste it in where you need it:

In [28]:
def get_detailed_variable_info(intake_catalog, experiment_name : str, variable : str | None = None) -> "pd.Dataframe":
    """
    Get detailed information about all the variables available in an experiment contained within the catalog.

    If a specific variable is passed, then the returned dataframe will be filtered to include only information
    about that variable

    Returns a pandas dataframe, reorganised to use the variable as the index.

    Parameters:
    -----------
    intake_catalog: 
        The variable holding the intake catalog. If you have opened the catalog using
        `cat = intake.cat.access_nri`, then `intake_catalog=cat`, etc.
    experiment_name: str
        The name of the experiment you are interested in. Eg. `experiment = "01deg_jra55v13_ryf9091"`
    variable: str | None
        If you want detailed information about just a single variable, then pass it here. For 
        example, if you only want information about potential temperature, pass `variable='pot_temp'`
    """
    from intake_esm.utils import MinimalExploder
    import polars as pl

    expt_ds = intake_catalog[experiment_name]
    df = MinimalExploder(expt_ds.esmcat.pl_df)()

    df = df.unique('variable').sort('variable')

    if variable is not None:
        df = df.filter(pl.col('variable') == variable)

    df = df.to_pandas().set_index("variable")

    return df

To get detailed info about all variables:

In [29]:
df = get_detailed_variable_info(catalog, experiment)
df.head(10)

,filename,path,file_id,frequency,start_date,end_date,variable_long_name,variable_standard_name,variable_cell_methods,variable_units,realm,temporal_label
variable,,,,,,,,,,,,
ANGLE,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",angle grid makes with latitude line on U grid,,,radians,seaIce,mean
ANGLET,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",angle grid makes with latitude line on T grid,,,radians,seaIce,mean
HTE,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",T cell width on East side,,,m,seaIce,mean
HTN,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",T cell width on North side,,,m,seaIce,mean
NCAT,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",category maximum thickness,,,m,seaIce,mean
TLAT,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",T grid center latitude,,,degrees_north,seaIce,mean
TLON,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",T grid center longitude,,,degrees_east,seaIce,mean
Tsfc_m,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",snow/ice surface temperature,,time: mean,C,seaIce,mean
ULAT,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",U grid center latitude,,,degrees_north,seaIce,mean
ULON,iceh.1900-01.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ice/OUTPUT/iceh.1900-01.nc,seaIce.1mon.d2:2.nc:5.ni:3600.nj:2700,1mon,"1900-01-01, 00:00:00","1900-02-01, 00:00:00",U grid center longitude,,,degrees_east,seaIce,mean

Say we are only interested in zonal wind stress, `tau_x`:

In [30]:
df = get_detailed_variable_info(catalog, experiment, 'tau_x')
df.head(10)

,filename,path,file_id,frequency,start_date,end_date,variable_long_name,variable_standard_name,variable_cell_methods,variable_units,realm,temporal_label
variable,,,,,,,,,,,,
tau_x,ocean_month.nc,/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v13_ryf9091/output000/ocean/ocean_month.nc,ocean.1mon.nv:2.xt_ocean:3600.xu_ocean:3600.yt_ocean:2700.yu_ocean:2700,1mon,"1900-01-01, 00:00:00","1900-04-01, 00:00:00",i-directed wind stress forcing u-velocity,surface_downward_x_stress,time: mean,N/m^2,ocean,mean

If you have any further questions after reading this notebook and the documentation linked from this notebook, please open an issue in the [ACCESS-NRI Intake catalog Github repo](https://github.com/ACCESS-NRI/access-nri-intake-catalog) or open topic on the [ACCESS-Hive forum](https://forum.access-hive.org.au/).

In [31]:
client.close()

___
## Some common troubleshooting steps


### Why have I got two datasets, not one?

Sometimes, you will wind up with a situation where you've searched for a variable like this:
```python
exptname = '01deg_jra55v140_iaf'
datastore = intake.cat.access_nri[exptname]
searched_ds = datastore.search(variable="temp", frequency="1mon")
temp = searched_ds.to_dask()
```
and get an error: 
```pytb
ValueError: Expected exactly one dataset. Received 2 datasets. Please refine your search on file_id, temporal_label or use `.to_dataset_dict()`.
```

In these instances, the first thing to do is check the number of `file_id`'s you have:
```python
>>> searched_ds.unique().file_id
['ocean.1mon.nv:2.st_edges_ocean:76.st_ocean:75.xt_ocean:3600.yt_ocean:2700',
 'ocean.1mon.st_edges_ocean:76.st_ocean:75.xt_ocean:3600.yt_ocean:2700']
```

Two file ID's means two datasets - but why?

The problem is that intake looks at *files*, and has to decide what fits together into one xarray mfdataset. Typically though, what you actually want is a variable.
These variables normally span a bunch of differnt files.
The way netCDF (a `.nc` file, the storage format we use for cliamte model outputs) stores variables and dimensions. 
Crucially, a variable doesn't need to span every single dimension in the file, just a subset. This is what causes the issue.

Imagine have a situation like this:

```
output000/
   file_1.nc # var Potential Temp with dims x,y,z and var SST with dims x,y
output001/
   file_1.nc # Just SST in this one, dims x and y, ie. just SST
```
Intake looks at this, and assumes that because `output000/file_1.nc` and `output001/file_1.nc` don't have the same dimensions, they can't be joined into a single dataset. This is true for some of the variables in the first dataset (ie. the Potential Temperature field would break if we tried this), but not all the variables in the dataset - it works just fine for the SST field.

Irritatingly, because intake works at the file level, we can't (currently) filter for some of the variables in the file without dragging all of them along for the ride. This means that if you have a model run where the dimensions of all the output files are inconsistent, intake will struggle to recognise what files should be joined together - at least today.

This will get better with the newer models, because the new ACCESS model's output a single variable per file - which means this issue can't occur.


### Why this might actually be a good thing (in this case)

In the example above, we can look at the last couple of files in the dataset to see what specifically has gone wrong:
```python
>>> searched_ds.df.path[-2:]
270    /g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v140_iaf/output243/ocean/ocean-3d-temp-1-monthly-mean-ym_2018_10.nc
271    /g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v140_iaf/output243/ocean/ocean-3d-temp-1-monthly-snap-ym_2018_11.nc
Name: path, dtype: object
```

Interesting - so we have a `mean` and a `snap`. This looks like we might have two different types of outputs - mean and snapshots. 
The `nv` in the first `file_id` conventionally refers to 'number of vertices' - ie, how many edges do we have. Typically, this applies to things like snapshots. Let's dig into the suggestion in the error message more deeply:

```python
>>> searched_df.unique().temporal_label
['mean', 'point']
```

As we suspected, we have a mean, and a point aggregation. So `'ocean.1mon.st_edges_ocean:76.st_ocean:75.xt_ocean:3600.yt_ocean:2700'` refers to the monthly mean dataset, and `'ocean.1mon.st_edges_ocean:76.st_ocean:75.xt_ocean:3600.yt_ocean:2700'` to the monthly snapshot datasets.

### General Advice - What to do if you have more datasets than you expected
In this instance, we had two datasets. If you get multiple datasets when you only expect one, the fastest way to work out what's going wrong is to just print out the datastore to the console:
```python
>>> searched_df
01deg_jra55v140_iaf catalog with 2 dataset(s) from 272 asset(s):

unique
filename	272
path	272
file_id	2
frequency	1
start_date	272
end_date	272
variable	11
variable_long_name	11
variable_standard_name	2
variable_cell_methods	3
variable_units	7
realm	1
temporal_label	2
derived_variable	0
```

From this, we can see that there are two of both `file_id` and `temporal_label`. This tells us that it's probably one of these that is telling us we have multiple datasets, so the next step is to try to filter on either. We know that either will work in this case, but we really have two temporal labels, so lets search on that:

```python
>>> searched_ds.search(temporal_label='mean')
01deg_jra55v140_iaf catalog with 1 dataset(s) from 244 asset(s):

unique
filename	244
path	244
file_id	1
frequency	1
start_date	244
end_date	244
variable	11
variable_long_name	11
variable_standard_name	2
variable_cell_methods	2
variable_units	7
realm	1
temporal_label	1
derived_variable	0
```

As expected, we now have a single dataset & can just load it.

If you run into a really complicated case, try using the interactive catalogue - [this link](https://access-nri.github.io/interactive-data-catalogue/#/datastore/01deg_jra55v140_iaf?frequency_filter=1mon&variable_filter=temp) takes us to the dataset we are looking at in this example. We can click around quite quickly to work out what the issue is, and copy back the working code once we're ready.